version: "3"

services:
   influxdb_log:
      image: hypriot/rpi-influxdb
      ports: 
         - "8086:8086"
      container_name: influxdb_amco
      restart: always
      environment:
         - INFLUXDB_INIT_PWD= "admin"
         - PRE_CREATE_DB= ev
      volumes:
         - ./data_collection/data:/var/lib/influxdb
      networks:
            internal:
               aliases:
                 - influxdb.docker.local


   grafana_log:
      image: grafana/grafana
      ports: 
         - "3000:3000"
      container_name: grafana_amco
      restart: always
      volumes:
         - grafana-db:/var/lib/grafana
         - grafana-log:/var/log/grafana
         - grafana-conf:/etc/grafana
      environment:
         - GF_AUTH_DISABLE_LOGIN_FORM=true
         - GF_AUTH_ANONYMOUS_ENABLED=true
         - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
         - GF_SECURITY_ALLOW_EMBEDDING=true

      networks:
            internal:
               aliases:
                 - grafana.docker.local
             
      depends_on:
           - influxdb_log
        


   mosquitto_log:
       image: pascaldevink/rpi-mosquitto
       ports:
          - "1883:1883"
       container_name: mosquitto_amco
       restart: always
       volumes:
           - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
           - ./mosquitto/data:/mosquitto/data
           - ./mosquitto/log:/mosquitto/log
       networks:
            internal:
               aliases:
                 - mqtt.docker.local



   mqtt_driver:
        image: mqtt_driver:v1
        build: ./data_collection/
        container_name: mqtt_driver_amco
        restart: always
        networks:
            internal:
               aliases:
                 - mqtt_driver.docker.local
        depends_on:
             - influxdb_log
             - mosquitto_log

   
   dashboard:
        image: amco_dashboard:v1
        build: ./user_interface/
        container_name: dashbaord_amco
        restart: always
        ports:
           - "9000:9000"
        networks:
            internal:
               aliases:
                 - dashboard.docker.local
        


networks:
     internal:

volumes:
     grafana-db:
        driver: local
     grafana-log:
        driver: local
     grafana-conf:
        driver: local
     data:
